# Azure Pipeline Definition for Model CI/CD

# Trigger on changes in the modeling folder and on the master branch                      
trigger:
  branches:
    include:
    - master

  paths:
    include:
    - code/*

stages:
# ML Build Stage
- stage: Build
  displayName: 'Model Build (code/model validation and training)'
  jobs:
  - job: ML_Build
    displayName: ML Build
    pool:
      vmImage: 'ubuntu-16.04'
    variables:
    - name: resourceGroupName
      value: devopsforaidev
    - name: resourceGroupLocation
      value: westeurope
    - name: amlWorkspaceName
      value: mlworkspacedevdeeikele
    - name: amlPipelineRunner
      value: code/pipelines/retrain_model.py

    steps:
    # Prepare the build environment
    - bash: echo "##vso[task.prependpath]$CONDA/bin"
      displayName: Add Conda to PATH

    - script: |
        conda env create -n agentenv --file code/build-and-release/agent-environment.yml
      displayName: Create Agent Anaconda environment

    # Run Code Health Check
    - template: ado-templates/codehealth.template.yml
      parameters:
        workingDirectory: "tests/"

    # ML Pipeline Experiment (before-publish)
    #   For long execution times, one could first run a training pipeline on a data sample to validate all
    #   pipeline steps complete; then run the pipeline on the full data set.
    - task: AzureCLI@1
      displayName: 'Generate AML Workspace Config File'
      inputs:
        azureSubscription: "my-service-connection"
        scriptLocation: inlineScript
        inlineScript: |
          subscription=$(az account list --query "[?isDefault].id | [0]" --output tsv)
          echo {\"subscription_id\":\"$subscription\", \"resource_group\":\"$(resourceGroupName)\", \"workspace_name\":\"$(amlWorkspaceName)\"} > .azureml/config.json

    - task: AzureCLI@2
      displayName: Run Training Pipeline (sample)
      inputs:
        azureSubscription: "my-service-connection"
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          source activate agentenv
          python $(amlPipelineRunner) --await_completion True

    - task: CopyFiles@2
      displayName: Copy Model Metadata (name and version)
      inputs:
        contents: 'outputs/models/**'
        targetFolder: $(Build.ArtifactStagingDirectory)

    # Optional for long training workflows
    # - task: AzureCLI@2
    #   displayName: Run Training Pipeline (a-sync)
    #   inputs:
    #     azureSubscription: "my-service-connection"
    #     scriptType: bash
    #     scriptLocation: inlineScript
    #     inlineScript: |
    #       source activate agentenv
    #       python $(amlPipelineRunner) --await_completion True

    # Publish model artifacts for release
    - task: PublishBuildArtifacts@1
      displayName: Publish ML Build Artifacts
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)
        artifactName: MLBuildArtifacts
