# Environment name
name:
# Environment version
version:
# Environment variables set for the run.
environmentVariables:
  EXAMPLE_ENV_VAR: EXAMPLE_VALUE
# Python details
python:
# user_managed_dependencies=True indicates that the environmentwill be user managed. False indicates that AzureML willmanage the user environment.
  userManagedDependencies: false
# The python interpreter path
  interpreterPath: python
# Path to the conda dependencies file to use for this run. If a project
# contains multiple programs with different sets of dependencies, it may be
# convenient to manage those environments with separate files.
  condaDependenciesFile: conda_dependencies.yml
# The base conda environment used for incremental environment creation.
  baseCondaEnvironment:
# Docker details
docker:
# Set True to perform this run inside a Docker container.
  enabled: true
# Base image used for Docker-based runs. Mutually exclusive with base_dockerfile.
  baseImage: mcr.microsoft.com/azureml/base:intelmpi2018.3-ubuntu16.04
# Base Dockerfile used for Docker-based runs. Mutually exclusive with base_image
  baseDockerfile:
# Set False if necessary to work around shared volume bugs.
  sharedVolumes: true
# Shared memory size for Docker container. Default is 2g.
  shmSize: 2g
# Extra arguments to the Docker run command.
  arguments: []
# Image registry that contains the base image.
  baseImageRegistry:
# DNS name or IP address of azure container registry(ACR)
    address:
# The username for ACR
    username:
# The password for ACR
    password:
# Spark details
spark:
# List of spark repositories.
  repositories: []
# The packages to use.
  packages: []
# Whether to precache the packages.
  precachePackages: false
# Databricks details
databricks:
# List of maven libraries.
  mavenLibraries: []
# List of PyPi libraries
  pypiLibraries: []
# List of RCran libraries
  rcranLibraries: []
# List of JAR libraries
  jarLibraries: []
# List of Egg libraries
  eggLibraries: []
# Inferencing stack version
inferencingStackVersion:
